version: 2.1

orbs:
  maven: circleci/maven@0.0.12
  codecov: codecov/codecov@1.0.2
  
jobs:
  build:
    steps:
      - codecov/upload:
          token: abea7830-9ee2-4e8c-bdb9-60e032c5c163

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
      - codecov/upload
  

